[project]
id = "tablia"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
port = 54323
email = "admin@tablia.io"
password = "admin"

[inbucket]
port = 54324

[auth]
site_url = "https://dev.tablia.io"
additional_redirect_urls = [
  "http://localhost:5174",
  "https://dev.tablia.io"
]

[auth.email]
enable_signup = true
enable_confirmations = false

[[auth.external.google]]
enabled = false
